### ISSUE TITLE
error importing `shadow_geometry` module

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/start-code#18]
Hi @dicaearchus, I am having an issue here:

https://github.com/GO-Eratosthenes/start-code/blob/c2f2c7063a29005a461691ed71c1178bd1d388b9/eratosthenes/preprocessing/shadow_geometry.py#L597

Is one suppose to continue after the `try..except` block even if `IndexError` is raised? If so, this should be `pass` I believe (but then `castLine` might remain undefined).

**Comment by dicaearchus** [comment]
Yes, I had the same error, as I refactored the function, as it was in a loop, but "return" will suffice, doesn't it?

**Comment by fnattino** [comment]
Yes, the `return` will immediately return a `None`, if the `IndexError` is raised. But then the list created in `list_occluder_and_casted` will be appended a `None`. Is this intended?  To skip these failing cases, one might also want to modify this:
https://github.com/GO-Eratosthenes/start-code/blob/c2f2c7063a29005a461691ed71c1178bd1d388b9/eratosthenes/preprocessing/shadow_geometry.py#L564
into:
```python
if castLine is not None:
  castList.append(castLine)
```

**Comment by fnattino** [comment]
Fixed with `return`
